package app.morphe.manager.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * Molt's colour identity.
 *
 * The palette is derived from the Molt icon rather than inherited from upstream:
 * the violet of the chameleon drives the primary tones, its mint highlights drive
 * the tertiary tones, and surfaces sit on a violet-leaning neutral so the whole app
 * reads as one piece with the icon. Tones follow the Material 3 roles
 * (40/90/10 in light, 80/30/90 in dark).
 */

val theme_light_primary = Color(0xFF521AB2)
val theme_light_onPrimary = Color(0xFFFFFFFF)
val theme_light_primaryContainer = Color(0xFFE2D9F2)
val theme_light_onPrimaryContainer = Color(0xFF160D26)
val theme_light_secondary = Color(0xFF5B4A82)
val theme_light_onSecondary = Color(0xFFFFFFFF)
val theme_light_secondaryContainer = Color(0xFFE4E1EA)
val theme_light_onSecondaryContainer = Color(0xFF18151E)
val theme_light_tertiary = Color(0xFF24756F)
val theme_light_onTertiary = Color(0xFFFFFFFF)
val theme_light_tertiaryContainer = Color(0xFFDCEFEE)
val theme_light_onTertiaryContainer = Color(0xFF102322)
val theme_light_error = Color(0xFFBA1A1A)
val theme_light_errorContainer = Color(0xFFFFDAD6)
val theme_light_onError = Color(0xFFFFFFFF)
val theme_light_onErrorContainer = Color(0xFF410002)
val theme_light_background = Color(0xFFFCFCFD)
val theme_light_onBackground = Color(0xFF19191A)
val theme_light_surface = Color(0xFFFCFCFD)
val theme_light_onSurface = Color(0xFF19191A)
val theme_light_surfaceVariant = Color(0xFFE5E4E7)
val theme_light_onSurfaceVariant = Color(0xFF4B4455)
val theme_light_outline = Color(0xFF7D6F90)
val theme_light_inverseOnSurface = Color(0xFFF2F2F3)
val theme_light_inverseSurface = Color(0xFF333135)
val theme_light_inversePrimary = Color(0xFFC4AEEA)
//val theme_light_shadow = Color(0xFF000000)
val theme_light_surfaceTint = Color(0xFF521AB2)
val theme_light_outlineVariant = Color(0xFFCBC7D1)
val theme_light_scrim = Color(0xFF000000)

val theme_dark_primary = Color(0xFFC4AEEA)
val theme_dark_onPrimary = Color(0xFF2B1551)
val theme_dark_primaryContainer = Color(0xFF3F1980)
val theme_dark_onPrimaryContainer = Color(0xFFE2D9F2)
val theme_dark_secondary = Color(0xFFC7C1D7)
val theme_dark_onSecondary = Color(0xFF2E283E)
val theme_dark_secondaryContainer = Color(0xFF453960)
val theme_dark_onSecondaryContainer = Color(0xFFE4E1EA)
val theme_dark_tertiary = Color(0xFFB4E4E0)
val theme_dark_onTertiary = Color(0xFF1B4B47)
val theme_dark_tertiaryContainer = Color(0xFF24756F)
val theme_dark_onTertiaryContainer = Color(0xFFDCEFEE)
val theme_dark_error = Color(0xFFFFB4AB)
val theme_dark_errorContainer = Color(0xFF93000A)
val theme_dark_onError = Color(0xFF690005)
val theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val theme_dark_background = Color(0xFF121016)
val theme_dark_onBackground = Color(0xFFE5E5E6)
val theme_dark_surface = Color(0xFF121016)
val theme_dark_onSurface = Color(0xFFE5E5E6)
val theme_dark_surfaceVariant = Color(0xFF4B4455)
val theme_dark_onSurfaceVariant = Color(0xFFCBC7D1)
val theme_dark_outline = Color(0xFF978DA5)
val theme_dark_inverseOnSurface = Color(0xFF19191A)
val theme_dark_inverseSurface = Color(0xFFE5E5E6)
val theme_dark_inversePrimary = Color(0xFF521AB2)
//val theme_dark_shadow = Color(0xFF000000)
val theme_dark_surfaceTint = Color(0xFFC4AEEA)
val theme_dark_outlineVariant = Color(0xFF4B4455)
val theme_dark_scrim = Color(0xFF000000)

val monochrome_light_primary = Color(0xFF565E68)
val monochrome_light_onPrimary = Color(0xFFFFFFFF)
val monochrome_light_primaryContainer = Color(0xFFDDE3EA)
val monochrome_light_onPrimaryContainer = Color(0xFF141B22)
val monochrome_light_secondary = Color(0xFF5B6170)
val monochrome_light_onSecondary = Color(0xFFFFFFFF)
val monochrome_light_secondaryContainer = Color(0xFFE0E4EA)
val monochrome_light_onSecondaryContainer = Color(0xFF181D28)
val monochrome_light_tertiary = Color(0xFF60616A)
val monochrome_light_onTertiary = Color(0xFFFFFFFF)
val monochrome_light_tertiaryContainer = Color(0xFFE4E5EC)
val monochrome_light_onTertiaryContainer = Color(0xFF1B1D24)
val monochrome_light_background = Color(0xFFF7F8FC)
val monochrome_light_onBackground = Color(0xFF191B20)
val monochrome_light_surface = Color(0xFFFFFFFF)
val monochrome_light_onSurface = Color(0xFF191B20)
val monochrome_light_surfaceVariant = Color(0xFFE7EAF1)
val monochrome_light_onSurfaceVariant = Color(0xFF444852)
val monochrome_light_outline = Color(0xFF747984)
val monochrome_light_outlineVariant = Color(0xFFC5C9D2)
val monochrome_light_inverseOnSurface = Color(0xFFF1F2F7)
val monochrome_light_inverseSurface = Color(0xFF2E3035)
val monochrome_light_inversePrimary = Color(0xFFC8CED8)
val monochrome_light_surfaceTint = Color(0xFF565E68)
val monochrome_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val monochrome_light_surfaceContainerLow = Color(0xFFF2F4F9)
val monochrome_light_surfaceContainer = Color(0xFFEEF1F7)
val monochrome_light_surfaceContainerHigh = Color(0xFFE9ECF3)
val monochrome_light_surfaceContainerHighest = Color(0xFFE3E6EE)
val monochrome_light_surfaceBright = Color(0xFFFFFFFF)
val monochrome_light_surfaceDim = Color(0xFFD9DDE5)

val monochrome_dark_primary = Color(0xFFC8CED8)
val monochrome_dark_onPrimary = Color(0xFF29313A)
val monochrome_dark_primaryContainer = Color(0xFF3E4650)
val monochrome_dark_onPrimaryContainer = Color(0xFFE3E8EF)
val monochrome_dark_secondary = Color(0xFFC4C9D8)
val monochrome_dark_onSecondary = Color(0xFF2D323D)
val monochrome_dark_secondaryContainer = Color(0xFF434956)
val monochrome_dark_onSecondaryContainer = Color(0xFFE0E5F2)
val monochrome_dark_tertiary = Color(0xFFC8CBD3)
val monochrome_dark_onTertiary = Color(0xFF2F3138)
val monochrome_dark_tertiaryContainer = Color(0xFF464852)
val monochrome_dark_onTertiaryContainer = Color(0xFFE5E7EF)
val monochrome_dark_background = Color(0xFF0B0C10)
val monochrome_dark_onBackground = Color(0xFFE4E6EC)
val monochrome_dark_surface = Color(0xFF131418)
val monochrome_dark_onSurface = Color(0xFFE4E6EC)
val monochrome_dark_surfaceVariant = Color(0xFF444852)
val monochrome_dark_onSurfaceVariant = Color(0xFFC5C9D2)
val monochrome_dark_outline = Color(0xFF8E929C)
val monochrome_dark_outlineVariant = Color(0xFF444852)
val monochrome_dark_inverseOnSurface = Color(0xFF191B20)
val monochrome_dark_inverseSurface = Color(0xFFE4E6EC)
val monochrome_dark_inversePrimary = Color(0xFF565E68)
val monochrome_dark_surfaceTint = Color(0xFFC8CED8)
val monochrome_dark_surfaceContainerLowest = Color(0xFF06070A)
val monochrome_dark_surfaceContainerLow = Color(0xFF111216)
val monochrome_dark_surfaceContainer = Color(0xFF17191E)
val monochrome_dark_surfaceContainerHigh = Color(0xFF202228)
val monochrome_dark_surfaceContainerHighest = Color(0xFF2B2E35)
val monochrome_dark_surfaceBright = Color(0xFF383B43)
val monochrome_dark_surfaceDim = Color(0xFF0B0C10)
